script = """
-3 < -2
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 29, 0, 0, 0, 3, 18, 29, 0, 0, 0, 2, 18, 5, 40]"
bytecode_length = 21
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_integer (value: 3)
12 \tneg
13 \tpush_integer (value: 2)
18 \tneg
19 \tint_lt
20 \tret
"""

[output.vm]
bytes_read = 22
instructions_executed = 7
jumps_performed = 0
max_stack_height = 2
stack_allocations = 6
