script = """
-0.0 >=. -0.0
"""

[output]
result = "true"
type = "boolean"

[output.compiler]
bytecode = "[0, 38, 4, 109, 97, 105, 110, 28, 0, 0, 0, 0, 18, 28, 0, 0, 0, 0, 18, 12, 19, 40]"
bytecode_length = 22
disassembled = """
0 \tComponent Count: 0

1 \t=== function chunk: main ===
7 \tpush_float (value: 0)
12 \tneg
13 \tpush_float (value: 0)
18 \tneg
19 \tfloat_lt
20 \tnot
21 \tret
"""

[output.vm]
bytes_read = 23
instructions_executed = 8
jumps_performed = 0
max_stack_height = 2
stack_allocations = 7
