script = """
3 is
    _
        "ok"
    _
        "not okay"
"""

[output]
error = """
    _
    \u001B[33m^\u001B[0m
Line 4.5: `is` expression cannot have multiple default arms (previously defined at line 2)"""
