script = '''
repeat = \s times
    s | repeat_part "" times

repeat_part = \s acc tt
    tt is
        t if t <= 1
            acc
        _
            "{acc}{s}" | repeat_part s (tt - 1)

"hey" | repeat 3
'''

[output]
error = """
???
Function not found: repeat_part"""
