#[derive(Debug, Clone, PartialEq)]
pub enum TokenKind {
    BackSlash,
    Bang,
    BangEqual,
    Context,
    Comma,
    Comment,
    Dot,
    Equal,
    EqualEqual,
    False,
    Float,
    Identifier,
    Integer,
    KeywordAnd,
    KeywordOr,
    KeywordIs,
    KeywordIf,
    LeftBrace,
    LeftBracket,
    LeftParen,
    LeftChevron,
    LeftChevronDot,
    LeftChevronEqual,
    LeftChevronEqualDot,
    Minus,
    MinusDot,
    NewLine,
    Percent,
    PercentDot,
    Pipe,
    Plus,
    PlusDot,
    RightBrace,
    RightBracket,
    RightParen,
    RightChevron,
    RightChevronDot,
    RightChevronEqual,
    RightChevronEqualDot,
    Slash,
    SlashDot,
    Space,
    Star,
    StarDot,
    StringConcat,
    SyntaxError(&'static str),
    Tab,
    Tag,
    Text,
    True,
    Underscore,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Position {
    pub line: usize,
    pub column: usize,
    // pub start: u32,
    // pub end: u32,

    // start and end *can* be extracted from the lexeme
    // start: usize,
    // length: usize,
}

#[derive(Debug, Clone, PartialEq)]
pub struct Token {
    pub kind: TokenKind,
    pub position: Position,
    pub lexeme: String, // TODO(anissen): Should probably be &'a str,
}
